# Generated by Django 6.0.7 on 2026-07-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=120)),
            ],
        ),
    ]
